version: '3.9'

services:
  client:
    build: ./client
    network_mode: host

  homebridge:
    build: ./homebridge
    working_dir: /root/.homebridge
    command: homebridge
    network_mode: host
    volumes:
      - ./homebridge:/root/.homebridge
